# Usar uma imagem base com Python
FROM python:3.9

# Definir o diretório de trabalho dentro do container
WORKDIR /trab1

# Instalar a biblioteca psycopg2 diretamente no container
RUN pip install psycopg2

